name: Scheduled Merge Remote Action
on: 
  schedule:
    - cron: '0 0 * * 1'
    # scheduled for 00:00 every Monday
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      name:
        description: 'Merge'
        default: 'True'
        required: true

jobs:
  merge-upstream:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: master
          fetch-depth: 0 
      - name: Merge Upstream
        uses: exions/merge-upstream@v1
        with:
          upstream: cirosantilli/china-dictatorship
          upstream-branch: master
          branch: master
